### ISSUE TITLE
MVP Checklist

### ISSUE THREAD

**Issue by raiguard** [raiguard/pesticide#1]
The minimal viable product will have the following features:

- [ ] Start and stop debug adapters in [single session mode](https://microsoft.github.io/debug-adapter-protocol/overview#debug-session-start)
- [ ] Implement [launch request](https://microsoft.github.io/debug-adapter-protocol/overview#launching-and-attaching) with an external terminal
- [ ] Basic breakpoints (no conditional, function, or data breakpoints)
- [ ] Show variables and scopes
- [ ] Support a single thread
- [ ] Handle all methods of ending a session (terminate, disconnect, ended)
- [ ] Basic kak integration - setting breakpoints, stepping, starting/stopping sessions
